### ISSUE TITLE
unable to compile library

### ISSUE THREAD

**Issue by b2labs33** [brglng/libwav#1]
~/eclipse-workspace/vinylgen/Debug/libwav/build$ cmake -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/build
benjamin@vostro:~/eclipse-workspace/vinylgen/Debug/libwav/build$ make
Scanning dependencies of target wave
[ 16%] Building C object CMakeFiles/wave.dir/src/wave.c.o
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c:296:1: warning: ‘static’ is not at beginning of declaration [-Wold-style-declaration]
 const static int wave_container_sizes[5] = {0, 1, 2, 4, 4};
 ^
In file included from /home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c:3:0:
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c: In function ‘wave_tell’:
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c:471:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         assert(pos >= header_size);
                    ^
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c: In function ‘wave_seek’:
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c:489:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (offset >= 0 && offset <= length) {
                               ^
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c: In function ‘wave_eof’:
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c:515:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
            ftell(wave->fp) == wave_get_header_size(wave) + wave->chunk.data_chunk.size;
                            ^
[ 33%] Linking C shared library libwave.so
[ 33%] Built target wave
Scanning dependencies of target wave_static
[ 50%] Building C object CMakeFiles/wave_static.dir/src/wave.c.o
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c:296:1: warning: ‘static’ is not at beginning of declaration [-Wold-style-declaration]
 const static int wave_container_sizes[5] = {0, 1, 2, 4, 4};
 ^
In file included from /home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c:3:0:
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c: In function ‘wave_tell’:
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c:471:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         assert(pos >= header_size);
                    ^
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c: In function ‘wave_seek’:
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c:489:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (offset >= 0 && offset <= length) {
                               ^
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c: In function ‘wave_eof’:
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/src/wave.c:515:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
            ftell(wave->fp) == wave_get_header_size(wave) + wave->chunk.data_chunk.size;
                            ^
[ 66%] Linking C static library libwave_static.a
[ 66%] Built target wave_static
Scanning dependencies of target diff-wave
[ 83%] Building C object app/diff-wave/CMakeFiles/diff-wave.dir/src/diff-wave.c.o
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/app/diff-wave/src/diff-wave.c:15:1: warning: ‘static’ is not at beginning of declaration [-Wold-style-declaration]
 const static char* appname = "diff-wave";
 ^
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/app/diff-wave/src/diff-wave.c: In function ‘container_size’:
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/app/diff-wave/src/diff-wave.c:122:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     } while (i < 8*sizeof(size_t));
                ^
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/app/diff-wave/src/diff-wave.c: In function ‘diff_file’:
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/app/diff-wave/src/diff-wave.c:147:12: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
     printf("  sample size: %u\n", wave_get_sample_size(in1));
            ^
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/app/diff-wave/src/diff-wave.c:150:12: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
     printf("  length: %u\n", wave_get_length(in1));
            ^
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/app/diff-wave/src/diff-wave.c:153:12: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
     printf("  sample size: %u\n", wave_get_sample_size(in2));
            ^
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/app/diff-wave/src/diff-wave.c:156:12: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
     printf("  length: %u\n", wave_get_length(in2));
            ^
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/app/diff-wave/src/diff-wave.c:206:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (j=0; j<readlen; ++j) {
                        ^
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/app/diff-wave/src/diff-wave.c:213:20: warning: passing argument 1 of ‘wave_write’ from incompatible pointer type [-Wincompatible-pointer-types]
         wave_write(bufout, readlen, out);
                    ^
In file included from /home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/app/diff-wave/src/diff-wave.c:11:0:
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/include/wave.h:68:13: note: expected ‘void **’ but argument is of type ‘double **’
 size_t      wave_write(void** buffers, size_t count, WaveFile* wave);
             ^
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/app/diff-wave/src/diff-wave.c: In function ‘main’:
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/app/diff-wave/src/diff-wave.c:370:5: warning: implicit declaration of function ‘diff_dir’ [-Wimplicit-function-declaration]
     diff_dir(in1name, in2name, outname, recursive);
     ^
[100%] Linking C executable diff-wave
CMakeFiles/diff-wave.dir/src/diff-wave.c.o : Dans la fonction « main » :
/home/benjamin/eclipse-workspace/vinylgen/Debug/libwav/app/diff-wave/src/diff-wave.c:370 : référence indéfinie vers « diff_dir »
collect2: error: ld returned 1 exit status
app/diff-wave/CMakeFiles/diff-wave.dir/build.make:95 : la recette pour la cible « app/diff-wave/diff-wave » a échouée
make[2]: *** [app/diff-wave/diff-wave] Erreur 1
CMakeFiles/Makefile2:159 : la recette pour la cible « app/diff-wave/CMakeFiles/diff-wave.dir/all » a échouée
make[1]: *** [app/diff-wave/CMakeFiles/diff-wave.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

**Comment by brglng** [comment]
Thank you for your report. It looks like the problem was in linking the executable program, but I could not understand your language. Could you provide an English version of the error log? However I believe the library itself was compiled correctly.

**Comment by imihajlow** [comment]
@brglng here's my output:
```[ 83%] Linking C executable diff-wave
CMakeFiles/diff-wave.dir/src/diff-wave.c.o: In function `db':
diff-wave.c:(.text+0x6b4): undefined reference to `log10'
CMakeFiles/diff-wave.dir/src/diff-wave.c.o: In function `main':
diff-wave.c:(.text+0x1333): undefined reference to `diff_dir'
collect2: error: ld returned 1 exit status
libwav/app/diff-wave/CMakeFiles/diff-wave.dir/build.make:95: recipe for target 'libwav/app/diff-wave/diff-wave' failed
make[2]: *** [libwav/app/diff-wave/diff-wave] Error 1
CMakeFiles/Makefile2:218: recipe for target 'libwav/app/diff-wave/CMakeFiles/diff-wave.dir/all' failed
make[1]: *** [libwav/app/diff-wave/CMakeFiles/diff-wave.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by brglng** [comment]
Fixed the issues in the latest commits and close this issue.

This library is in alpha stage and has not been maintained for a long time. The library should work fine, but please do not rely on the current API. API changes are planned.
