### ISSUE TITLE
Missing security policy

### ISSUE THREAD

**Issue by gson1703** [brglng/libwav#11]
I would like to report a potential security issue privately, but it is not clear how to do that as the repository has neither a SECURITY.md nor any obvious contact information for the author.

**Comment by brg1ng** [comment]
Please feel free to email me at zhaosheng.pan@sololand.moe .

**Comment by brglng** [comment]
Fixed in [c2d3144](https://github.com/brglng/libwave/commit/c2d31448d4240d3359ea77962b599fd85f0eb4e7)
