### ISSUE TITLE
Macros typos on windows platform in wave.h

### ISSUE THREAD

**Issue by Xtinc** [brglng/libwav#13]
in wave.h file, line 34-37,
a type mistake happenned which made Macro 

#if defined(_MSC_VER)
    #define WAVE_API __declspec(dllexport)
#else

 to

 #if defined(_MSV_VER)
    #define WAVE_API __declspec(dllexport)
#else

it seems that MSC_VER was misspelled as MSV_VER, cause a compiler error on windwos

**Comment by Xtinc** [comment]
This lib does a small but nice work.
another suggest is the macro which detects BIG-ENDIAN or LITTLE-ENDIAN was also broken on windows

**Comment by brglng** [comment]
Fixed in 72bbb7b.
