### ISSUE TITLE
Visual Studio 2022: 'WAVE_FORMAT_PCM': macro redefinition

### ISSUE THREAD

**Issue by djipi** [brglng/libwav#14]
When using the library, Visual Studio 2022 issue a warning.
C:\SDK\WAV\libwave\include\wave.h(81,9): warning C4005: 'WAVE_FORMAT_PCM': macro redefinition

I wanted to report it as it is the only warning issued during the compilation, and I do not know if you track them.

**Comment by brglng** [comment]
Hi @djipi , it is sad that there is already a `WAVE_FORMAT_PCM` macro in Windows headers. I have to consider what the best way is to solve this issue. There may have to be a breakage of API.

**Comment by djipi** [comment]
Hi @brglng , well, it is unfortunate. But it looks like the Windows macro has the same value than your own.
To avoid the redefinition, may be you can check if the define is already existing?

**Comment by brglng** [comment]
@djipi Please check if this issue is fixed in the latest commit.

**Comment by djipi** [comment]
Thank you @brglng , the redefinition has disappeared.
