### ISSUE TITLE
wav_set_format doesn't properly set block_align?

### ISSUE THREAD

**Issue by oskarvonephesos** [brglng/libwav#6]
Hi there!
I'm using your library to write a single channel of floats to a wav file. To open the file I run:
WavFile* fp;
fp = wav_open(file_path, restrict_mode);
wav_set_format(fp, WAV_FORMAT_IEEE_FLOAT);
wav_set_sample_size(fp, sizeof(float));
wav_set_num_channels(fp, 1);
wav_set_sample_rate(fp, SR);

Calling wav_set_sample_size is necessary, because otherwise I get incorrect files (which I think my have to do with block_align -- I have posted a picture: the upper audio is produced by the code shown above, the lower picture is the audio produced without wav_set_sample_size. On import, Audacity et al warn about a corrupted header). It does seem quite redundant, though, that I specify the format as floats and set the sample_size to be sizeof(float) as well. 
<img width="836" alt="Screen Shot 2021-03-10 at 3 22 20 PM" src="https://user-images.githubusercontent.com/46396332/110643516-74e20d00-81b4-11eb-8457-cba6f169ff58.png">

**Comment by brglng** [comment]
@oskarvonephesos I cannot reproduce the issue in this test https://github.com/brglng/libwav/blob/master/tests/write_f32/main.c . Could you please post your code?

**Comment by brglng** [comment]
@oskarvonephesos Please checkout the latest commit, thanks.
